<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYNuX2fw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYNuX2fw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYNuX2fw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYNuX2fw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYNuX2fw\App_KernelDevDebugContainer([
    'container.build_hash' => 'YNuX2fw',
    'container.build_id' => '20363857',
    'container.build_time' => 1599585636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYNuX2fw');
