<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'cabinet' => [[], ['_controller' => 'App\\Controller\\CabinetController::index'], [], [['text', '/cabinet']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\CabinetController::home'], [], [['text', '/']], [], []],
    'connexion_show' => [[], ['_controller' => 'App\\Controller\\CabinetController::login'], [], [['text', '/connexion']], [], []],
    'deconnexion_show' => [[], ['_controller' => 'App\\Controller\\CabinetController::logout'], [], [['text', '/deconnexion']], [], []],
    'patient' => [[], ['_controller' => 'App\\Controller\\CabinetController::patient'], [], [['text', '/patient']], [], []],
    'registration' => [[], ['_controller' => 'App\\Controller\\CabinetController::registration'], [], [['text', '/registration']], [], []],
    'modifier' => [['id'], ['_controller' => 'App\\Controller\\CabinetController::registration'], [], [['text', '/modifier'], ['variable', '/', '[^/]++', 'id', true], ['text', '/registration']], [], []],
    'newConsultation' => [[], ['_controller' => 'App\\Controller\\CabinetController::newConsultation'], [], [['text', '/newConsultation']], [], []],
];
